DIS:NC:18x275:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/18x275/minQ2=1000/DIS_NC_18x275_minQ2=1000.csv"
        - "DIS/NC/18x275/minQ2=100/DIS_NC_18x275_minQ2=100.csv"
        - "DIS/NC/18x275/minQ2=10/DIS_NC_18x275_minQ2=10.csv"
        - "DIS/NC/18x275/minQ2=1/DIS_NC_18x275_minQ2=1.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_1to10.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_10to100.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_100to1000.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_1000to10000.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_1to10.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_10to100.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_100to1000.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_1000to10000.csv"

DIS:NC:18x275:timings:
  extends: .timings
  needs:
    - DIS:NC:18x275:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/18x275/minQ2=1000/DIS_NC_18x275_minQ2=1000.csv"
        - "DIS/NC/18x275/minQ2=100/DIS_NC_18x275_minQ2=100.csv"
        - "DIS/NC/18x275/minQ2=10/DIS_NC_18x275_minQ2=10.csv"
        - "DIS/NC/18x275/minQ2=1/DIS_NC_18x275_minQ2=1.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_1to10.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_10to100.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_100to1000.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_noRad_ep_18x275_q2_1000to10000.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_1to10.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_10to100.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_100to1000.csv"
        - "DIS/NC/18x275/DJANGOH4.6.21-1.0_NC_Rad_ep_18x275_q2_1000to10000.csv"

DIS:NC:18x275:collect:
  extends: .collect
  needs: 
    - DIS:NC:18x275:timings
